### ISSUE TITLE
Technically not an "issue"

### ISSUE THREAD

**Issue by ZacharySims** [geooot/gradedapp#4]
George,
Technically this is not an issue, and I will delete this after your help, but for developing the app, what software/IDE did you use? I've been experimenting around with a few, I used Eclipse for the longest time but since I have now moved on to HTML and more applications worthy of release I wanted something with a sleeker, Interface, perhaps one specifically designed for HTML5 or app creation. I test ran Intel XDK and it wasn't bad but lacked documentation and general community support, I am currently using Visual Studio and that is definitely better so far, but I feel its still not there. Anyway since you obviously have some experience, and I most definitely like how the end result of Graded looks, in your opinion, which development environment do you think is best and which ones specifically did you use for this App?

Thanks mate!
-Zachary Sims

**Comment by geooot** [comment]
Hello Zachary,

Thanks for the complement on the app! So graded is a hybrid HTML/JS app which I made using Apache Cordova. Cordova is pretty much the base for Intel XDK and other frameworks. I use the Cordova CLI and a HTML IDE called WebStorm (its not free, but they offer a student licence).

As far as documentation is concerned, Cordova's Documentation is pretty good. It shows how to use the Cordova CLI and work with many plugins. https://cordova.apache.org/plugins/

Also here is a tutorial that I used to set up a Cordova apps. It is well documented and I suggest using it to at least learn the basics.

https://ccoenraets.github.io/cordova-tutorial/create-cordova-project.html

If you have any more questions, I'll be glad to answer.

Cheers,
George T

**Comment by ZacharySims** [comment]
Awesome! Thanks mate! That is very helpful
I've been making progress on an app and this will surely advance the
development of it. Thank you for your time George!

Thanks!
-Zachary Sims

On Saturday, November 28, 2015, George Thayamkery <notifications@github.com>
wrote:

> Closed #4 <https://github.com/geooot/gradedapp/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geooot/gradedapp/issues/4#event-476871801>.
>


-- 
*- Zachary Sims*
